"""Add feature store tables

Revision ID: 2d2b1502a4b2
Revises: 001
Create Date: 2025-11-16 17:17:03.908758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2d2b1502a4b2'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_weights_last_updated', table_name='portfolio_weights')
    op.drop_index('ix_portfolio_weights_portfolio_id', table_name='portfolio_weights')
    op.drop_index('ix_portfolio_weights_portfolio_stock', table_name='portfolio_weights')
    op.drop_index('ix_portfolio_weights_stock_id', table_name='portfolio_weights')
    op.drop_table('portfolio_weights')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_backtest_strategy_dates', table_name='backtest_results')
    op.drop_index('idx_backtest_symbol', table_name='backtest_results')
    op.drop_index('ix_backtest_results_id', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('ix_reports_report_type', table_name='reports')
    op.drop_index('ix_reports_stock_id', table_name='reports')
    op.drop_index('ix_reports_stock_type', table_name='reports')
    op.drop_index('ix_reports_user_created', table_name='reports')
    op.drop_index('ix_reports_user_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_signal_strategy_created', table_name='signals')
    op.drop_index('idx_signal_symbol', table_name='signals')
    op.drop_index('ix_signals_id', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_portfolios_last_updated', table_name='portfolios')
    op.drop_index('ix_portfolios_user_created', table_name='portfolios')
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('idx_position_portfolio_status', table_name='positions')
    op.drop_index('idx_position_symbol', table_name='positions')
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_alerts_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_market_data_symbol_timestamp', table_name='market_data')
    op.drop_index('idx_market_data_timestamp', table_name='market_data')
    op.drop_index('ix_market_data_id', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('idx_trade_portfolio_created', table_name='trades')
    op.drop_index('idx_trade_symbol', table_name='trades')
    op.drop_index('ix_trades_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_strategy_active', table_name='strategies')
    op.drop_index('idx_strategy_user_type', table_name='strategies')
    op.drop_index('ix_strategies_id', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_backups_created_status', table_name='backups')
    op.drop_index('ix_backups_status', table_name='backups')
    op.drop_table('backups')
    op.drop_index('ix_zerodha_tokens_access_token', table_name='zerodha_tokens')
    op.drop_index('ix_zerodha_tokens_id', table_name='zerodha_tokens')
    op.drop_table('zerodha_tokens')
    op.drop_index('ix_paper_trades_id', table_name='paper_trades')
    op.drop_index('ix_paper_trades_symbol', table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index('ix_stocks_industry', table_name='stocks')
    op.drop_index('ix_stocks_last_updated', table_name='stocks')
    op.drop_index('ix_stocks_sector', table_name='stocks')
    op.drop_index('ix_stocks_sector_industry', table_name='stocks')
    op.drop_index('ix_stocks_symbol', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('ix_stock_portfolio_portfolio_id', table_name='stock_portfolio')
    op.drop_index('ix_stock_portfolio_stock_id', table_name='stock_portfolio')
    op.drop_table('stock_portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_portfolio',
    sa.Column('stock_id', sa.INTEGER(), nullable=True),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], )
    )
    op.create_index('ix_stock_portfolio_stock_id', 'stock_portfolio', ['stock_id'], unique=False)
    op.create_index('ix_stock_portfolio_portfolio_id', 'stock_portfolio', ['portfolio_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('sector', sa.VARCHAR(), nullable=True),
    sa.Column('industry', sa.VARCHAR(), nullable=True),
    sa.Column('market_cap', sa.FLOAT(), nullable=True),
    sa.Column('last_price', sa.FLOAT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stocks_symbol', 'stocks', ['symbol'], unique=1)
    op.create_index('ix_stocks_sector_industry', 'stocks', ['sector', 'industry'], unique=False)
    op.create_index('ix_stocks_sector', 'stocks', ['sector'], unique=False)
    op.create_index('ix_stocks_last_updated', 'stocks', ['last_updated'], unique=False)
    op.create_index('ix_stocks_industry', 'stocks', ['industry'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=4), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_trades_symbol', 'paper_trades', ['symbol'], unique=False)
    op.create_index('ix_paper_trades_id', 'paper_trades', ['id'], unique=False)
    op.create_table('zerodha_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('access_token', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zerodha_tokens_id', 'zerodha_tokens', ['id'], unique=False)
    op.create_index('ix_zerodha_tokens_access_token', 'zerodha_tokens', ['access_token'], unique=1)
    op.create_table('backups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backups_status', 'backups', ['status'], unique=False)
    op.create_index('ix_backups_created_status', 'backups', ['created_at', 'status'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=False),
    sa.Column('symbols', sqlite.JSON(), nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategies_id', 'strategies', ['id'], unique=False)
    op.create_index('idx_strategy_user_type', 'strategies', ['user_id', 'type'], unique=False)
    op.create_index('idx_strategy_active', 'strategies', ['is_active'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=False),
    sa.Column('position_id', sa.INTEGER(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('side', sa.VARCHAR(), nullable=False),
    sa.Column('pnl', sa.FLOAT(), nullable=False),
    sa.Column('fees', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_id', 'trades', ['id'], unique=False)
    op.create_index('idx_trade_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('idx_trade_portfolio_created', 'trades', ['portfolio_id', 'created_at'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('open', sa.FLOAT(), nullable=False),
    sa.Column('high', sa.FLOAT(), nullable=False),
    sa.Column('low', sa.FLOAT(), nullable=False),
    sa.Column('close', sa.FLOAT(), nullable=False),
    sa.Column('volume', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_id', 'market_data', ['id'], unique=False)
    op.create_index('idx_market_data_timestamp', 'market_data', ['timestamp'], unique=False)
    op.create_index('idx_market_data_symbol_timestamp', 'market_data', ['symbol', 'timestamp'], unique=1)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('alert_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('average_price', sa.FLOAT(), nullable=False),
    sa.Column('current_price', sa.FLOAT(), nullable=False),
    sa.Column('unrealized_pnl', sa.FLOAT(), nullable=False),
    sa.Column('realized_pnl', sa.FLOAT(), nullable=False),
    sa.Column('stop_loss', sa.FLOAT(), nullable=True),
    sa.Column('take_profit', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    op.create_index('idx_position_symbol', 'positions', ['symbol'], unique=False)
    op.create_index('idx_position_portfolio_status', 'positions', ['portfolio_id', 'status'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    op.create_index('ix_portfolios_user_created', 'portfolios', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_portfolios_last_updated', 'portfolios', ['last_updated'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('signal_type', sa.VARCHAR(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_id', 'signals', ['id'], unique=False)
    op.create_index('idx_signal_symbol', 'signals', ['symbol'], unique=False)
    op.create_index('idx_signal_strategy_created', 'signals', ['strategy_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=True),
    sa.Column('report_type', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_index('ix_reports_user_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_reports_stock_type', 'reports', ['stock_id', 'report_type'], unique=False)
    op.create_index('ix_reports_stock_id', 'reports', ['stock_id'], unique=False)
    op.create_index('ix_reports_report_type', 'reports', ['report_type'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('initial_balance', sa.FLOAT(), nullable=False),
    sa.Column('final_balance', sa.FLOAT(), nullable=False),
    sa.Column('total_return', sa.FLOAT(), nullable=False),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=False),
    sa.Column('max_drawdown', sa.FLOAT(), nullable=False),
    sa.Column('win_rate', sa.FLOAT(), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_results_id', 'backtest_results', ['id'], unique=False)
    op.create_index('idx_backtest_symbol', 'backtest_results', ['symbol'], unique=False)
    op.create_index('idx_backtest_strategy_dates', 'backtest_results', ['strategy_id', 'start_date', 'end_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('permissions', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('portfolio_weights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=True),
    sa.Column('stock_id', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_weights_stock_id', 'portfolio_weights', ['stock_id'], unique=False)
    op.create_index('ix_portfolio_weights_portfolio_stock', 'portfolio_weights', ['portfolio_id', 'stock_id'], unique=False)
    op.create_index('ix_portfolio_weights_portfolio_id', 'portfolio_weights', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_weights_last_updated', 'portfolio_weights', ['last_updated'], unique=False)
    # ### end Alembic commands ### 